### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by splitice** [giom/nginx_accept_language_module#6]
On review I noticed this module is prone to poor scalability.

Scales roughly `O(n*m)` where n is the number of languages supplied in the header and m is the number of languages supported.

If m is sufficiently large this module will cease to perform well.

**Comment by giom** [comment]
Hi, you're probably right, I only ever used it with m = 3 languages. I do not currently use this module since we switched to using a CDN in front of nginx for the use case I had and we now do the normalization in the CDN. However, I will spend time to clean up and look at any PR this week.

**Comment by splitice** [comment]
@giom I think replacing the array with a ngx_hash_t would work.

**Comment by splitice** [comment]
Closing in favor of #7
